---
title: "viz"
author: "ignacia-rivera"
date: "April 16, 2016"
output: html_document
---

## Data and setup

```{r}
library(dplyr)
library(ggplot2)
library(gapminder)

# preview data, the way this dataframe is presented is different than the usual one, because we have first call dyplr
gapminder

# get range of available data
summary(gapminder)

```



#plot
```{r, echo=FALSE}

g = gapminder %>%
  filter(year==2007) %>%   # most recent year 
  mutate(pop_m = pop/1e6)  # population, millions

# plot scatterplot of most recent year 
s = ggplot(g, aes(x=gdpPercap, y=lifeExp, size=pop, col=continent)) +
  geom_point()+
  ggtitle('Health & Wealth of Nations for 2007') +
  xlab('GDP per capita ($/year)') +
  ylab('Life expectancy (years)') +
  scale_colour_discrete(name='Continent') +
  scale_size_continuous(name='Population (M)') +
  theme_bw()
ggsave('hans.png')

```

```{r maps, echo=FALSE}

#install.packages('tmap')
library(tmap)
library(magrittr)
library(dplyr)


# load world spatial polygons
data(World)

# inspect values in World
World@data %>% tbl_df()

# gapminder countries not in World. skipping for now
g %>% 
  anti_join(World@data, by=c('country'='name')) %>% 
  arrange(desc(pop))

# World countries not in gapminder. skipping for now
World@data %>% 
  anti_join(g, by=c('name'='country')) %>% 
  arrange(desc(pop_est)) %>%
  select(iso_a3, name, pop_est)

# join gapminder data to World
World@data = World@data %>%
  left_join(g, by=c('name'='country'))

# make map
m = tm_shape(World) +
    tm_polygons('lifeExp', palette='RdYlGn', id='name', title='Life expectancy (years)', auto.palette.mapping=F) +
    tm_style_gray() + tm_format_World()
m

# show interactive map
tmap_leaflet(m)
```


